# NOTE: update this with your service name
service: bestsup-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"
functions:
  create:
    handler: create.main
    events:
      - http:
          path: blog
          method: post
          cors: true
          authorizer: aws_iam
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /blogs/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: blogs/{id}
          method: get
          cors: true
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /blogs
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: blogs
          method: get
          cors: true
  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /blogs/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: blogs/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /blogs/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: blogs/{id}
          method: delete
          cors: true
          authorizer: aws_iam